/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/shared/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "primary": "hsl(var(--primary) / <alpha-value>)",
        "onPrimary": "hsl(var(--onPrimary) / <alpha-value>)",
        "primaryContainer": "hsl(var(--primaryContainer) / <alpha-value>)",
        "onPrimaryContainer": "hsl(var(--onPrimaryContainer) / <alpha-value>)",
        "primaryFixed": "hsl(var(--primaryFixed) / <alpha-value>)",
        "onPrimaryFixed": "hsl(var(--onPrimaryFixed) / <alpha-value>)",
        "primaryFixedDim": "hsl(var(--primaryFixedDim) / <alpha-value>)",
        "onPrimaryFixedVariant": "hsl(var(--onPrimaryFixedVariant) / <alpha-value>)",
        "secondary": "hsl(var(--secondary) / <alpha-value>)",
        "onSecondary": "hsl(var(--onSecondary) / <alpha-value>)",
        "secondaryContainer": "hsl(var(--secondaryContainer) / <alpha-value>)",
        "onSecondaryContainer": "hsl(var(--onSecondaryContainer) / <alpha-value>)",
        "secondaryFixed": "hsl(var(--secondaryFixed) / <alpha-value>)",
        "onSecondaryFixed": "hsl(var(--onSecondaryFixed) / <alpha-value>)",
        "secondaryFixedDim": "hsl(var(--secondaryFixedDim) / <alpha-value>)",
        "onSecondaryFixedVariant": "hsl(var(--onSecondaryFixedVariant) / <alpha-value>)",
        "tertiary": "hsl(var(--tertiary) / <alpha-value>)",
        "onTertiary": "hsl(var(--onTertiary) / <alpha-value>)",
        "tertiaryContainer": "hsl(var(--tertiaryContainer) / <alpha-value>)",
        "onTertiaryContainer": "hsl(var(--onTertiaryContainer) / <alpha-value>)",
        "tertiaryFixed": "hsl(var(--tertiaryFixed) / <alpha-value>)",
        "onTertiaryFixed": "hsl(var(--onTertiaryFixed) / <alpha-value>)",
        "tertiaryFixedDim": "hsl(var(--tertiaryFixedDim) / <alpha-value>)",
        "onTertiaryFixedVariant": "hsl(var(--onTertiaryFixedVariant) / <alpha-value>)",
        "error": "hsl(var(--error) / <alpha-value>)",
        "onError": "hsl(var(--onError) / <alpha-value>)",
        "errorContainer": "hsl(var(--errorContainer) / <alpha-value>)",
        "onErrorContainer": "hsl(var(--onErrorContainer) / <alpha-value>)",
        "outline": "hsl(var(--outline) / <alpha-value>)",
        "background": "hsl(var(--background) / <alpha-value>)",
        "onBackground": "hsl(var(--onBackground) / <alpha-value>)",
        "surface": "hsl(var(--surface) / <alpha-value>)",
        "onSurface": "hsl(var(--onSurface) / <alpha-value>)",
        "surfaceVariant": "hsl(var(--surfaceVariant) / <alpha-value>)",
        "onSurfaceVariant": "hsl(var(--onSurfaceVariant) / <alpha-value>)",
        "inverseSurface": "hsl(var(--inverseSurface) / <alpha-value>)",
        "inverseOnSurface": "hsl(var(--inverseOnSurface) / <alpha-value>)",
        "inversePrimary": "hsl(var(--inversePrimary) / <alpha-value>)",
        "shadow": "hsl(var(--shadow) / <alpha-value>)",
        "surfaceTint": "hsl(var(--surfaceTint) / <alpha-value>)",
        "outlineVariant": "hsl(var(--outlineVariant) / <alpha-value>)",
        "scrim": "hsl(var(--scrim) / <alpha-value>)",
        "surfaceContainerHighest": "hsl(var(--surfaceContainerHighest) / <alpha-value>)",
        "surfaceContainerHigh": "hsl(var(--surfaceContainerHigh) / <alpha-value>)",
        "surfaceContainer": "hsl(var(--surfaceContainer) / <alpha-value>)",
        "surfaceContainerLow": "hsl(var(--surfaceContainerLow) / <alpha-value>)",
        "surfaceContainerLowest": "hsl(var(--surfaceContainerLowest) / <alpha-value>)",
        "surfaceBright": "hsl(var(--surfaceBright) / <alpha-value>)",
        "surfaceDim": "hsl(var(--surfaceDim) / <alpha-value>)"
      },
      boxShadow: {
        elevation1: '0 1px 2px 0 rgba(0,0,0,0.3), 0 1px 3px 1px rgba(0,0,0,0.15)',
        elevation2: '0 1px 2px 0 rgba(0,0,0,0.3), 0 2px 6px 2px rgba(0,0,0,0.15)',
        elevation3: '0 1px 3px 0 rgba(0,0,0,0.3), 0 4px 8px 3px rgba(0,0,0,0.15)',
        elevation4: '0 2px 3px 0 rgba(0,0,0,0.3), 0 6px 10px 4px rgba(0,0,0,0.15)',
        elevation5: '0 4px 4px 0 rgba(0,0,0,0.3), 0 8px 12px 6px rgba(0,0,0,0.15)',
      },
    },
  },
  plugins: [],
}
